[package]
name = "easyfem_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gauss-quad = "0.1.8"
nalgebra = "0.32.3"
easyfem_mesh = { path = "../easyfem_mesh" }
